### ISSUE TITLE
Loading in chroot

### ISSUE THREAD

**Issue by binkybear** [seemoo-lab/bcm-public#4]
First off, great work on all of this!

I've started working on a custom ROM with your firmware/binaries built in.  Right now it runs CM 14.1 with custom kernel (supports external wireless/HID/etc) and comes with Nethunter preinstalled.  Here is example: https://transfer.sh/EYM2R/nethunter-hammerheadcaf-ota-bae271eade.zip.  It can be installed with [TWRP](https://dl.twrp.me/hammerheadcaf/).  Chroot needs to be downloaded through app.

I don't expect any help on this but I wanted to bring this up.  The libfakeioctl.so does not load inside a kali chroot (probably all chroots) on device.  I can recompile inside chroot: 
[libfakeioctl.zip](https://github.com/seemoo-lab/bcm-public/files/608093/libfakeioctl.zip)

However, running LD_PRELOAD=libfakeioctl.so inside chroot works fine for tcpdump (even shows monitor mode) but running airodump-ng results in reboot:

Kernel oops: http://pastebin.com/WHB50Tzg

It appears to be related to set channel (thats all I got from it).

I had monitor mode working in chroot previously using a custom ioctl inject and the small kernel patch (not the firmware modification).

Any help would be appreciated.  Works great outside chroot also ;)

**Comment by matthiasseemoo** [comment]
The bcmdhd driver seems to have a problem to set 40 MHz channels, therefore, Daniel wrote a patch for the driver that you could try: https://github.com/seemoo-lab/bcm-public/blob/90bed6e1c3ad70ddc23ccf44033b152e0db300b6/kernel_patches/40mhz_channels_5GHz.patch

In addition, if you create your own rom, then you can also modify the kernel and the driver, hence, it would make sense to add real monitor mode capabilities to the driver, so that you do not need to use nexutil to activate monitor mode anymore and you would not need the libfakeioctl hack.

btw. we continued our development on the firmware in our new repository, with which you can also build firmwares for other devices: https://github.com/seemoo-lab/nexmon

**Comment by binkybear** [comment]
@matthiasseemoo - Thanks for getting back so quickly.  I will try the patch.  

My impression and experience with the previous kernel/firmware was that it only allowed for monitor mode and you couldn't switch back to a managed mode.  I don't think there was a fakeioctl built in either to show monitor mode.  I could be wrong though.

I will try the suggested kernel patch later today, thanks!  I've been looking at the nexmon repo and plan on testing out patched firmware on rpi3 soon also.

**Comment by binkybear** [comment]
Applying kernel patch appears to fix problem and I can no run with monitor mode in chroot.  Thanks!

**Comment by AutinDroid** [comment]
I know the issue is closed, but I was just wondering when/if the completed CM14.1 NetHunter ROM will be released along with the source code. It would be nice if there is an early release of the ROM, even if not stable, that has working frame injection for wlan0. I have tried the ROM listed in transfer.sh (In fact, I'm typing on the ROM). Its a great ROM, very stable with all the nethunter features, and I will continue using it until there is an update. Keep up the great work!

**Comment by nethunteros** [comment]
@AutinDroid - https://gist.github.com/binkybear/8f0f4eee292d5263372f47c3c3edd08e

Expect a switch from CAF hopefully to make it more stable.
